apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fogproject-mysql
  name: fogproject-mysql
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fogproject-mysql

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fogproject-pmagic
  name: fogproject-pmagic
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: fogproject-pmagic

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: fogproject-images
  name: fogproject-images
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1501Gi
  storageClassName: fogproject-images
