apiVersion: v1
kind: PersistentVolume
metadata:
  name: fogproject-mysql
spec:
  capacity:
    storage: 1501Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fogproject-mysql
  mountOptions:
    - nolock
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/fogproject/mysql
