apiVersion: v1
kind: PersistentVolume
metadata:
  name: fogproject-mysql
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fogproject-mysql
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/fog/data/mysql
    user: admin
    secretRef:
      name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fogproject-pmagic
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fogproject-pmagic
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/fog/data/pmagic
    user: admin
    secretRef:
      name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fogproject-images
spec:
  capacity:
    storage: 1501Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: fogproject-images
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/fog/images
    user: admin
    secretRef:
      name: ceph-secret
