apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-mariadb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-mariadb
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/wordpress/mariadb
      user: admin
      secretRef:
        name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-wordpress
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: wordpress-wordpress
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/wordpress/wordpress
      user: admin
      secretRef:
        name: ceph-secret
