kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mrbs-mariadb
  labels:
    app: mrbs-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: mrbs-mariadb

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mrbs
  labels:
    app: mrbs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mrbs