apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mosquitto-mosquitto-data
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/mosquitto/data
      user: admin
      secretRef:
        name: ceph-secret