apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mosquitto
    protocol: mqtt
  name: mosquitto-mosquitto-data
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mosquitto-mosquitto-data
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/mosquitto/mosquitto/data
