apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/ensino/rabbitmq/
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: rabbitmq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: ensino
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rabbitmq

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: ensino
spec:
  rules:
    - host: rabbitmq.sj.ifsc.edu.br
      http:
        paths:
          - backend:
              serviceName: rabbitmq-mgmt
              servicePort: 15672
            path: /
  tls:
    - hosts:
        - rabbitmq.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq-mgmt
  namespace: ensino
spec:
  ports:
    - name: rabbitmq-mgmt
      port: 15672
      protocol: TCP
      targetPort: 15672
  selector:
    app: rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: ensino
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: rabbitmq
      port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    app: rabbitmq
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: ensino
spec:
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-default-pass
                  name: rabbitmq
            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: rabbitmq-default-user
                  name: rabbitmq
          image: docker.io/rabbitmq:3-management
          livenessProbe:
            httpGet:
              path: /
              port: 15672
            initialDelaySeconds: 30
          name: rabbitmq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          readinessProbe:
            httpGet:
              path: /
              port: 15672
            initialDelaySeconds: 30
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 256m
              memory: 128
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq
      volumes:
        - name: rabbitmq
          persistentVolumeClaim:
            claimName: rabbitmq
