apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: zabbix-db
  mountOptions:
    - nolock
    - nfsvers=3  
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/zabbix/db

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-scripts
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: zabbix-scripts
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/zabbix/scripts