apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-db
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: zabbix-db

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-scripts
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: zabbix-scripts