apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-mariadb
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: moodle-mariadb
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/moodle/mariadb
    user: admin
    secretRef:
      name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-moodle
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: moodle-moodle
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/moodle
    user: admin
    secretRef:
      name: ceph-secret