apiVersion: v1
data:
  nsswitch.conf: |
      passwd:         compat ldap
      group:          compat ldap
      shadow:         compat ldap
      gshadow:        files
      hosts:          files myhostname mdns4_minimal [NOTFOUND=return] dns
      networks:       files
      protocols:      db files
      services:       db files
      ethers:         db files
      rpc:            db files
      netgroup:       nis
kind: ConfigMap
metadata:
  name: nsswitch-conf

---
apiVersion: v1
data:
  ldap.conf: |
    base dc=cefetsc,dc=edu,dc=br
    uri ldap://ldap.sj.ifsc.edu.br ldap://ldap.ifsc.edu.br
    ldap_version 3
kind: ConfigMap
metadata:
  labels:
    app: cups
  name: ldap-conf
  namespace: testes

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: cups
  name: cups
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Mi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/cups
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: cups

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cups
  name: cups
  namespace: testes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: cups

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cups
  name: cups
  namespace: testes
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: cups
      port: 631
      protocol: TCP
      targetPort: 631
  selector:
    app: cups
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cups
  name: cups
  namespace: testes
spec:
  selector:
    matchLabels:
      app: cups
  template:
    metadata:
      labels:
        app: cups
    spec:
      containers:
        - env:
          - name: ROOT_PASSWD
            valueFrom:
              secretKeyRef:
                key: root-passwd
                name: cups
          image: cticsjeifsc/cups
          name: cups
          ports:
            - containerPort: 631
          resources:
            limits:
              cpu: 2
              memory: 1Gi
            requests:
              cpu: 128m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/nsswitch.conf
              name: nsswitch-conf
              readOnly: true
              subPath: nsswitch.conf
            - mountPath: /etc/ldap/ldap.conf
              name: ldap-conf
              readOnly: true
              subPath: ldap.conf
            - mountPath: /etc/cups
              name: cups
      volumes:
        - configMap:
            name: nsswitch-conf
          name: nsswitch-conf
        - configMap:
            name: ldap-conf
          name: ldap-conf
        - name: cups
          persistentVolumeClaim:
            claimName: cups
