apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-conf
data:
  ldap.conf: |-
    base dc=cefetsc,dc=edu,dc=br
    uri ldap://ldap.sj.ifsc.edu.br ldap://ldap.ifsc.edu.br
    ldap_version 3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ldap-ldap-conf
data:
  ldap.conf: |-
    base dc=cefetsc,dc=edu,dc=br
    uri ldap://ldap.sj.ifsc.edu.br ldap://ldap.ifsc.edu.br
    ldap_version 3

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pam-ldap-conf
data:
  pam_ldap.conf: |-
    base dc=cefetsc,dc=edu,dc=br
    uri ldap://ldap.sj.ifsc.edu.br ldap://ldap.ifsc.edu.br
    ldap_version 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: libnss-ldap-conf
data:
  libnss-ldap.conf: |-
    base dc=cefetsc,dc=edu,dc=br
    uri ldap://ldap.sj.ifsc.edu.br ldap://ldap.ifsc.edu.br
    ldap_version 3

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nsswitch-ldap-conf
data:
  nsswitch.conf: |
    passwd:         compat ldap
    group:          compat ldap
    shadow:         compat ldap
    gshadow:        files

    hosts:          files myhostname mdns4_minimal [NOTFOUND=return] dns
    networks:       files

    protocols:      db files
    services:       db files
    ethers:         db files
    rpc:            db files

    netgroup:       nis

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pam-common-session
data:
  common-session: |-
    session [default=1]                     pam_permit.so
    session requisite                       pam_deny.so
    session required                        pam_permit.so
    session required        pam_unix.so
    session optional                        pam_ldap.so
    session optional        pam_systemd.so
    session required        pam_mkhomedir.so skel=/etc/skel umask=077
