apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-mongo-database
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rocketchat-mongo-database
  mountOptions:
    - nolock    
  nfs:
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/rocket.chat_att/mongo
    server: storage1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocketchat-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: rocketchat-data
  mountOptions:
    - nolock    
  nfs:
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/rocket.chat_att/data
    server: storage1