apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: ensino
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: minecraft
