apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: minecraft
  name: minecraft
  namespace: ensino
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: minecraft
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/ensino/minecraft
