apiVersion: v1
kind: Service
metadata:
  name: ensino-jogos-minecraft
  namespace: ensino
  labels:
    app: minecraft
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: minecraft
      port: 25565
      protocol: TCP
      targetPort: 25565
    - name: rcon
      port: 25575
      protocol: TCP
      targetPort: 25575
  selector:
    app: minecraft-minecraft
  type: LoadBalancer
