apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/motioneye/config
  storageClassName: motioneye-config
  mountOptions:
    - nolock
    - nfsvers=3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-gravacoes
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/motioneye/gravacoes
  storageClassName: motioneye-gravacoes
  mountOptions:
    - nolock
    - nfsvers=3
