apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-config
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: motioneye-config
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/motioneye/config
      user: admin
      secretRef:
        name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: motioneye-gravacoes
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: motioneye-gravacoes
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/motioneye/gravacoes
      user: admin
      secretRef:
        name: ceph-secret
