apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: bind9
  name: bind9
  namespace: producao
spec:
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
      name: bind9
    spec:
      containers:
        - image: "cticsjeifsc/bind9:latest"
          name: bind9
          ports:
            - containerPort: 53
              protocol: UDP
            - containerPort: 53
              protocol: TCP
          resources:
            limits:
              cpu: 2
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/bind/named.conf
              name: bind9-conf
              readOnly: true
              subPath: named.conf
      hostNetwork: true
      volumes:
        - secret:
            secretName: bind9
          name: bind9-conf
