---
apiVersion: v1
data:
  named.conf: |-
    options {
      directory "/var/bind";
      listen-on {
        any;
      };
      allow-transfer {
        none;
      };
      allow-recursion {
        none;
      };
      recursion no;
      version none;
    };
    masters sje {
      191.36.8.2;
    };
    zone "sj.ifsc.edu.br" IN {
      type slave;
      masters {
        sje;
      };
    };
    zone "8-15.8.36.191.in-addr.arpa" IN {
      type slave;
      masters {
        sje;
      };
    };
kind: ConfigMap
metadata:
  name: bind9

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind9
  name: bind9-udp
  namespace: testes
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    app: bind9
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bind9
  name: bind9-tcp
  namespace: testes
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
  selector:
    app: bind9
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bind9
  name: bind9
  namespace: testes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
      name: bind9
    spec:
      containers:
        - image: "cticsjeifsc/bind9:latest"
          name: bind9
          ports:
            - containerPort: 53
          resources:
            limits:
              cpu: 2
              memory: 256Mi
            requests:
              cpu: 125m
              memory: 32Mi
          volumeMounts:
            - mountPath: /etc/bind/named.conf
              name: bind9-conf
              readOnly: true
              subPath: named.conf
      volumes:
        - configMap:
            name: bind9
          name: bind9-conf

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: bind9
  namespace: testes
spec:
  maxReplicas: 4
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bind9
