apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: pocketmine-mp
  name: pocketmine-mp-data
  namespace: ensino
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: pocketmine-mp-data
