kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: wiki
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
spec:
  tls:
    - hosts:
        - wiki.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard
  rules:
    - host: wiki.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: wiki
              servicePort: 80
