apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-mariadb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/mediawiki/mariadb
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: wiki-mariadb

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  cephfs:
    monitors:
      - "10.10.10.1:6789"
      - "10.10.10.5:6789"
      - "10.10.10.6:6789"
    path: /kubernetes/ifsc/sje/srv/mediawiki/wiki
    secretRef:
      name: ceph-secret
    user: admin
  storageClassName: wiki

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wiki-mariadb
  name: wiki-mariadb
  namespace: producao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: wiki-mariadb

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: wiki
  name: wiki
  namespace: producao
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wiki

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
  name: wiki
  namespace: producao
spec:
  rules:
    - host: wiki.sj.ifsc.edu.br
      http:
        paths:
          - backend:
              serviceName: wiki
              servicePort: 80
            path: /
  tls:
    - hosts:
        - wiki.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wiki-mariadb
  name: wiki-mariadb
  namespace: producao
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: wiki-mariadb

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wiki
  name: wiki
  namespace: producao
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: wiki

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wiki-mariadb
  name: wiki-mariadb
  namespace: producao
spec:
  selector:
    matchLabels:
      app: wiki-mariadb
  template:
    metadata:
      labels:
        app: wiki-mariadb
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Recife
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-root-password
                  name: wiki-mariadb
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mysql-database
                  name: wiki-mariadb
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-user
                  name: wiki-mariadb
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: wiki-mariadb
          image: "mariadb:10.3"
          name: wiki-mariadb
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              cpu: 2
              memory: 6Gi
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: wiki-mariadb
              subPath: mysql
      volumes:
        - name: wiki-mariadb
          persistentVolumeClaim:
            claimName: wiki-mariadb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wiki
  name: wiki
  namespace: producao
spec:
  selector:
    matchLabels:
      app: wiki
  template:
    metadata:
      labels:
        app: wiki
    spec:
      containers:
        - env:
            - name: TZ
              value: America/Recife
          image: "cticsjeifsc/mediawiki:1.31.10"
          livenessProbe:
            failureThreshold: 6
            httpGet:
              path: /index.php/Página_principal
              port: 80
              scheme: HTTP
            initialDelaySeconds: 60
            timeoutSeconds: 10
          name: wiki
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/www/html/extensions
              name: wiki-data
              subPath: extensions
            - mountPath: /var/www/html/images
              name: wiki-data
              subPath: images
            - mountPath: /var/www/html/skins
              name: wiki-data
              subPath: skins
            - mountPath: /var/www/html/LocalSettings.php
              name: wiki-data
              subPath: LocalSettings.php
      volumes:
        - name: wiki-data
          persistentVolumeClaim:
            claimName: wiki
