apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mariadb
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/mediawiki/mariadb
    user: admin
    secretRef:
      name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mediawiki
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mediawiki
  cephfs:
    monitors:
    - 10.10.10.1:6789
    - 10.10.10.5:6789
    - 10.10.10.6:6789
    path: /kubernetes/ifsc/sje/srv/mediawiki
    user: admin
    secretRef:
      name: ceph-secret
