apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mariadb
  mountOptions:
    - nolock
  nfs:
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mariadb
    server: 191.36.8.71

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mediawiki
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mediawiki
  mountOptions:
    - nolock
  nfs:
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mediawiki
    server: 191.36.8.71
