kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiki-mariadb
  labels:
    app: wiki-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: wiki-mariadb

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: wiki
  labels:
    app: wiki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wiki