apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mariadb
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mariadb
  mountOptions:
    - nolock
  nfs:
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mariadb
    server: storage1

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediawiki-mediawiki
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mediawiki-mediawiki
  mountOptions:
    - nolock
  nfs:
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/saas/srv/mediawiki/mediawiki
    server: storage1
