##### É necessário criar os seguintes diretórios executando os comandos abaixo em algum servidor proxmox
# cd /mnt/pve/cephfs/kubernetes/ifsc/sje/srv
# mkdir -p bareos/config/{client,director,storage,webui}
# mkdir -p bareos/data/{director,storage}
# mkdir -p bareos/pgsql
# chown -R 105:106 bareos
#####

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-db
  labels:
    app: bareos-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-db
    spec:
      containers:
      - name: bareos-db
        image: postgres:9.3
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-db-password
                key: bareos-db-password
          - name: TZ
            value: "America/Recife"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-db-postgresql
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: bareos-db-password
        secret:
          secretName: bareos-db-password
      - name: pv-bareos-db-postgresql
        persistentVolumeClaim:
          claimName: pv-bareos-db-postgresql

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-dir
  labels:
    app: bareos-dir
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-dir
    spec:
      containers:
      - name: bareos-dir
        image: barcus/bareos-director:18-ubuntu-pgsql
        env:
          - name: TZ
            value: "America/Recife"
          - name: ADMIN_MAIL
            value: humbertos@ifsc.edu.br,gabriel.souza@ifsc.edu.br,marcelo.muniz@ifsc.edu.br,rmartins@ifsc.edu.br
          - name: BAREOS_FD_HOST
            value: bareos-fd
          - name: BAREOS_FD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-fd-password
                key: bareos-fd-password
          - name: BAREOS_SD_HOST
            value: bareos-sd
          - name: BAREOS_SD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-sd-password
                key: bareos-sd-password
          - name: BAREOS_WEBUI_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-webui-password
                key: bareos-webui-password
          - name: DB_HOST
            value: bareos-db
          - name: PGHOST
            value: bareos-db
          - name: PGUSER
            value: postgres
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-db-password
                key: bareos-db-password
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-db-password
                key: bareos-db-password
          - name: DB_PORT
            value: "5432"
          - name: SMTP_HOST
            value: bareos-smtpd
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-dir-data
          mountPath: /var/lib/bareos
        - name: pv-bareos-dir-etc
          mountPath: /etc/bareos
      volumes:
      - name: bareos-sd-password
        secret:
          secretName: bareos-sd-password      
      - name: bareos-db-password
        secret:
          secretName: bareos-db-password
      - name: pv-bareos-dir-data
        persistentVolumeClaim:
          claimName: pv-bareos-dir-data
      - name: pv-bareos-dir-etc
        persistentVolumeClaim:
          claimName: pv-bareos-dir-etc

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-fd
  labels:
    app: bareos-fd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-fd
    spec:
      containers:
      - name: bareos-fd
        image: barcus/bareos-client:18-ubuntu
        env:
          - name: BAREOS_FD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-fd-password
                key: bareos-fd-password
          - name: TZ
            value: "America/Recife"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-fd-etc
          mountPath: /etc/bareos
        - name: pv-bareos-fd-dir-data
          mountPath: /var/lib/bareos-director
      volumes:
      - name: bareos-fd-password
        secret:
          secretName: bareos-fd-password
      - name: pv-bareos-fd-etc
        persistentVolumeClaim:
          claimName: pv-bareos-fd-etc
      - name: pv-bareos-fd-dir-data
        persistentVolumeClaim:
          claimName: pv-bareos-fd-dir-data

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-sd
  labels:
    app: bareos-sd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-sd
    spec:
      containers:
      - name: bareos-sd
        image: barcus/bareos-storage:18-ubuntu
        env:
          - name: BAREOS_SD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-sd-password
                key: bareos-sd-password
          - name: TZ
            value: "America/Recife"
        ports:
        - name: bareos
          containerPort: 9103
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-sd-data
          mountPath: /var/lib/bareos/storage
        - name: pv-bareos-sd-etc
          mountPath: /etc/bareos
      volumes:
      - name: bareos-sd-password
        secret:
          secretName: bareos-sd-password
      - name: pv-bareos-sd-data
        persistentVolumeClaim:
          claimName: pv-bareos-sd-data
      - name: pv-bareos-sd-etc
        persistentVolumeClaim:
          claimName: pv-bareos-sd-etc

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-webui
  labels:
    app: bareos-webui
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-webui
    spec:
      containers:
      - name: bareos-webui
        image: barcus/bareos-webui:18-ubuntu
        env:
          - name: BAREOS_DIR_HOST
            value: bareos-dir
          - name: TZ
            value: "America/Recife"
        ports:
        - name: bareos
          containerPort: 80
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
        volumeMounts:
        - name: pv-bareos-webui
          mountPath: /etc/bareos-webui
      volumes:
      - name: pv-bareos-webui
        persistentVolumeClaim:
          claimName: pv-bareos-webui

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bareos-smtpd
  labels:
    app: bareos-smtpd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: bareos-smtpd
    spec:
      containers:
      - name: bareos-smtpd
        image: namshi/smtp
        env:
          - name: TZ
            value: "America/Recife"
          - name: SMARTHOST_ADDRESS
            value: "hermes.ifsc.edu.br"
          - name: SMARTHOST_ALIASES
            value: "*.ifsc.edu.br"
          - name: SMARTHOST_PORT
            value: "587"
          - name: SMARTHOST_USER
            valueFrom:
              secretKeyRef:
                name: bareos-smtpd-user
                key: bareos-smtpd-user  
          - name: SMARTHOST_PASSWORD
            valueFrom:
              secretKeyRef:
                name: bareos-smtpd-password
                key: bareos-smtpd-password                                 
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
      volumes:
      - name: bareos-smtpd-password
        secret:
          secretName: bareos-smtpd-password
      - name: bareos-smtpd-user
        secret:
          secretName: bareos-smtpd-user

