apiVersion: v1
kind: PersistentVolume
metadata:
  name: hub-db-dir
spec:
  capacity:
    storage: 11002Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/jupyter/db
