apiVersion: v1
data:
  styling.inc: |-
    <?php

    // $Id$

    // DEFAULT THEME

    // ***** COLOURS ************************
    // Colours used in MRBS.    All the colours are defined here as PHP variables

    $body_background_color          = "#d6e6da";    // background colour for the main body
    $standard_font_color            = "#005817";    // default font color
    $header_font_color              = "#ffffff";    // font color for text in headers
    $highlight_font_color           = "#f93c32";    // used for highlighting text (eg links, errors)
    $colour_key_font_color          = $standard_font_color;    // used in the colour key table

    $banner_back_color              = "#438748";    // background colour for banner
    $banner_border_color            = $body_background_color;    // border colour for banner
    $banner_font_color              = $header_font_color;       // font colour for banner

    $header_back_color              = $banner_back_color;  // background colour for headers

    $admin_table_header_back_color  = $header_back_color;     // background colour for header and also border colour for table cells
    $admin_table_header_sep_color   = $body_background_color; // vertical separator colour in header
    $admin_table_header_font_color  = $header_font_color;     // font colour for header
    $admin_table_border_color       = "#438748";

    $main_table_border_color        = $body_background_color; // border colour for day/week/month tables - outside
    $main_table_header_border_color = $body_background_color; // border colour for day/week/month tables - header
    $main_table_body_h_border_color = "#d6e6da";              // border colour for day/week/month tables - body, horizontal
    $main_table_body_v_border_color = $body_background_color; // border colour for day/week/month tables - body, vertical
    $main_table_month_color         = "#ffffff";    // background colour for days in the month view
    $main_table_month_invalid_color = "#d1d9de";    // background colour for invalid days in the month view
    $main_table_slot_invalid_color  = "#d1d9de";    // background colour for invalid slots in the day and week views
    $main_table_labels_back_color   = $header_back_color;     // background colour for the row labels column

    // border colours for the main table when it is printed.     These are used by mrbs-print.css.php
    $main_table_border_color_print        = "#879AA8";    // border colour for the main table (print view)
    $main_table_header_border_color_print = "#879AA8";    // border colour for day/week/month tables - header (print view)
    $main_table_body_h_border_color_print = "#879AA8";    // border colour for day/week/month tables - body, horizontal (print view)
    $main_table_body_v_border_color_print = "#879AA8";    // border colour for day/week/month tables - body, vertical (print view)

    // font colours for the main table when it is printed
    $header_font_color_print        = "#0B263B";
    $anchor_link_color_header_print = "#0B263B";

    $report_table_border_color      = $standard_font_color;
    $report_h2_border_color         = $banner_back_color;     // border colour for <h2> in report.php
    $report_h3_border_color         = "#879AA8";              // border colour for <h2> in report.php

    $search_table_border_color      = $standard_font_color;

    $site_faq_entry_border_color    = "#3CCD3";

    $trailer_border_color           = $standard_font_color;

    $anchor_link_color              = $standard_font_color;        // link color
    $anchor_visited_color           = $anchor_link_color;          // link color (visited)
    $anchor_hover_color             = $highlight_font_color;       // link color (hover)

    $anchor_link_color_banner       = $header_font_color;          // link color
    $anchor_visited_color_banner    = $anchor_link_color_banner;   // link color (visited)
    $anchor_hover_color_banner      = $anchor_link_color_banner;   // link color (hover)

    $anchor_link_color_header       = $header_font_color;          // link color
    $anchor_visited_color_header    = $anchor_link_color_header;   // link color (visited)
    $anchor_hover_color_header      = $anchor_link_color_header;   // link color (hover)

    $column_hidden_color            = $main_table_month_invalid_color;    // hidden days in the week and month views
    $calendar_hidden_color          = "#0828fd";                          // hidden days in the mini-cals
    $row_even_color                 = "#ffffff";        // even rows in the day and week views
    $row_odd_color                  = "#d6e6da";        // even rows in the day and week views
    $row_highlight_color            = "#f93c32";        // used for highlighting a row
    //$row_highlight_color            = "#ffec00";        // used for highlighting a row

    $help_highlight_color           = "#FFFFFF";        // highlighting text on the help page  -- Página de ajuda

    $multiple_control_color         = "#FFFFFF";        // background colour for the multiple booking controls

    // These are the colours used for distinguishing between the dfferent types of bookings in the main
    // displays in the day, week and month views
    $color_types = array(
        'A' => "#ffff99",
        'B' => "#99cccc",
        'C' => "#ffffcd",
        'D' => "#cde6e6",
        'E' => "#6dd9c4",
        'F' => "#82adad",
        'G' => "#ccffcc",
        'H' => "#d9d982",
        'I' => "#99cc66",
        'J' => "#e6ffe6");

    // colours used for pending.php and bookings awaiting approval
    $outstanding_color         = "#FFF36C"; // font colour for the outstanding reservations message in the header
    $pending_header_back_color = $header_back_color;; // background colour for series headers
    $series_entry_back_color   = "#FFFCDA"; // background colour for entries in a series
    $pending_control_color     = "#FFF36C"; // background colour for the series +/- controls in pending.php

    // ***** DIMENSIONS *******************
    $banner_border_width          = '0';  // (px)  border width for the outside of the banner
    $banner_border_cell_width     = '1';  // (px)  border width for the cells of the banner
    $main_table_border_width      = '0';  // (px)  border width for the outside of the main day/week/month tables
    $main_table_cell_border_width = '1';  // (px)  border width for the cells of the main day/week/month tables
    $main_cell_height             = '17'; // (px)  height of the cells in the main day/week tables


    // ***** FONTS ************************
    $standard_font_family  = "Arial, 'Arial Unicode MS', Verdana, sans-serif";
kind: ConfigMap
metadata:
  labels:
    app: mrbs-reservas
  name: mrbs-reservas-conf
  namespace: producao

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mrbs-reservas-mariadb
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: mrbs-reservas-mariadb
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/mrbs-reservas/mariadb
      user: admin
      secretRef:
        name: ceph-secret

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mrbs-reservas-mariadb
  namespace: producao
  labels:
    app: mrbs-reservas-mariadb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: mrbs-reservas-mariadb

---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: reservas
  namespace: producao
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 32m
spec:
  tls:
    - hosts:
        - reservas.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard
  rules:
    - host: reservas.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: mrbs-reservas
              servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: mrbs-reservas-mariadb
  namespace: producao
  labels:
    app: mrbs-reservas-mariadb
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mrbs-reservas-mariadb

---
apiVersion: v1
kind: Service
metadata:
  name: mrbs-reservas
  namespace: producao
  labels:
    app: mrbs-reservas
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: mrbs-reservas

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mrbs-reservas-mariadb
  namespace: producao
  labels:
    app: mrbs-reservas-mariadb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrbs-reservas-mariadb
    spec:
      containers:
      - name: mrbs-reservas-mariadb
        image: mariadb:10.3
        env:
        - name: TZ
          value: "America/Recife"
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mrbs-reservas-mariadb
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mrbs-reservas-mariadb
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mrbs-reservas-mariadb
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mrbs-reservas-mariadb
              key: mysql-password
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mrbs-reservas-mariadb
          subPath: mysql
        resources:
          limits:
            memory: 512Mi
            cpu: 1
          requests:
            memory: 256Mi
            cpu: 300m
      volumes:
        - name: mrbs-reservas-mariadb
          persistentVolumeClaim:
            claimName: mrbs-reservas-mariadb

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mrbs-reservas
  namespace: producao
  labels:
    app: mrbs-reservas
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mrbs-reservas
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - "mrbs-reservas-mariadb"
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: mrbs-reservas
        image: cticsjeifsc/mrbs:1.7.5
        env:
          - name: TZ
            value: "America/Recife"
        ports:
        - name: http
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /admin.php
            port: 80
            scheme: HTTP
          initialDelaySeconds: 60
          timeoutSeconds: 10
          failureThreshold: 6
        volumeMounts:
        - mountPath: "/var/www/html/config.inc.php"
          name: mrbs-reservas
          readOnly: true
          subPath: config.inc.php       
        - mountPath: /var/www/html/Themes/default/styling.inc
          name: mrbs-reservas-conf
          subPath: styling.inc
        resources:
          limits:
            memory: 256Mi
            cpu: 1
          requests:
            memory: 128Mi
            cpu: 300m
      volumes:
        - name: mrbs-reservas
          secret:
            secretName: mrbs-reservas      
        - configMap:
            name: mrbs-reservas-conf
          name: mrbs-reservas-conf
