apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic-ceph-rbd
parameters:
  adminId: admin
  adminSecretName: ceph-secret-rbd
  adminSecretNamespace: producao
  fsType: ext4
  imageFeatures: layering
  imageFormat: "2"
  monitors: "10.10.10.1:6789, 10.10.10.5:6789, 10.10.10.6:6789"
  pool: kube
  userId: kube
  userSecretName: ceph-user-secret-rbd
  userSecretNamespace: producao
provisioner: kubernetes.io/rbd
