apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: dynamic-ceph-rbd
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.10.10.1:6789, 10.10.10.5:6789, 10.10.10.6:6789
  adminId: admin
  adminSecretName: ceph-secret-rbd
  adminSecretNamespace: producao
  pool: kube
  userId: kube
  userSecretName: ceph-user-secret-rbd
  userSecretNamespace: producao
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"