kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: hugo
spec:
  tls:
    - hosts:
        - nuvem.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard
  rules:
    - host: nuvem.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: hugo
              servicePort: 80
