apiVersion: v1
kind: PersistentVolume
metadata:
  name: hugo-web
spec:
  capacity:
    storage: 110Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hugo-web
  mountOptions:
    - nolock
    - nfsvers=3 
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/hugo/output

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: hugo-hugo-output
spec:
  capacity:
    storage: 111Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hugo-hugo-output
  mountOptions:
    - nolock
    - nfsvers=3 
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/hugo/output

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: hugo-hugo-src
spec:
  capacity:
    storage: 112Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: hugo-hugo-src
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/hugo/src
