apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hugo-web
  name: hugo-web
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 110Mi
  storageClassName: hugo-web

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hugo-hugo-output
  name: hugo-hugo-output
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 111Mi
  storageClassName: hugo-hugo-output

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: hugo-hugo-src
  name: hugo-hugo-src
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 112Mi
  storageClassName: hugo-hugo-src
