apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: omnet
spec:
  minReplicas: 1
  maxReplicas: 2
  metrics:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: omnet
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

