apiVersion: v1
kind: PersistentVolume
metadata:
  name: usuarios-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: usuarios-home
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: servicos-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: servicos-etc
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/users/etc
