kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kit-lanche-mariadb-dump
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: kit-lanche-mariadb-dump

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kit-lanche-mariadb-base
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kit-lanche-mariadb-base

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kit-lanche-code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kit-lanche-code