apiVersion: v1
kind: Service
metadata:
  labels:
    app: kit-lanche
  name: kit-lanche
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: kit-lanche
