apiVersion: v1
kind: PersistentVolume
metadata:
  name: octave-home
spec:
  capacity:
    storage: 10011Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/home
  mountOptions:
    - nolock
    - nfsvers=3

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: octave-users
spec:
  capacity:
    storage: 94Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/users
  mountOptions:
    - nolock
    - nfsvers=3
