apiVersion: v1
kind: Service
metadata:
  name: octave
  labels:
    app: octave
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2223
      protocol: TCP
      targetPort: 22
  selector:
    app: octave
  type: LoadBalancer
