---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: openldap
  name: openldap
  namespace: testes
spec:
  ports:
    - name: ldap
      port: 389
      protocol: TCP
      targetPort: 1024
  selector:
    app: openldap
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: openldap
  name: openldap
  namespace: testes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
      name: openldap
    spec:
      containers:
        - image: "cticsjeifsc/openldap:latest"
          name: openldap
          ports:
            - containerPort: 1024
          resources:
            limits:
              cpu: 1
              memory: "1Gi"
            requests:
              cpu: "125m"
              memory: "128Mi"
          volumeMounts:
            - mountPath: /etc/openldap/slapd.conf
              name: openldap-conf
              readOnly: true
              subPath: slapd.conf
      volumes:
        - name: openldap-conf
          secret:
            secretName: openldap
