kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: awx
  namespace: awx
  annotations:
    #
    # Solução para liberar somente à redes definidas
    nginx.ingress.kubernetes.io/whitelist-source-range: "191.36.0.0/17,2804:1454::/32,172.30.0.0/24"
spec:
  tls:
    - hosts:
        - awx.sj.ifsc.edu.br
      secretName: tls-ifsc-sje-wildcard
  rules:
    - host: awx.sj.ifsc.edu.br
      http:
        paths:
          - path: /
            backend:
              serviceName: awx-web-svc
              servicePort: 80
