apiVersion: v1
kind: Service
metadata:
  name: eagle
  labels:
    app: eagle
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2227
      protocol: TCP
      targetPort: 22
  selector:
    app: eagle
  type: LoadBalancer
