apiVersion: v1
kind: Service
metadata:
  name: eagle
  labels:
    app: eagle
spec:
  externalIPs:
#    - "191.36.8.1"
    - "191.36.8.5"
#    - "191.36.8.9"
    - "191.36.8.11"
#    - "191.36.8.21"
#    - "191.36.8.22"
#    - "191.36.8.23"
#    - "191.36.8.24"
    - "191.36.8.25"
#    - "191.36.8.26"
#    - "191.36.8.27"
  ports:
    - name: ssh
      port: 2227
      protocol: TCP
      targetPort: 22
  selector:
    app: eagle
  type: LoadBalancer
