# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qgis
  labels:
    app: qgis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: qgis
    spec:
      containers:
      - name: qgis
        image: cticsjeifsc/qgis
        ports:
        - name: ssh
          containerPort: 22
        resources:
            requests:
              cpu: 4
              memory: 2Gi
            limits:
              cpu: 8
              memory: 6Gi        