apiVersion: v1
kind: PersistentVolume
metadata:
  name: cronjobattusuarios-path
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: cronjobattusuarios-path
  mountOptions:
    - nolock
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/users