kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cronjobattusuarios-path
  labels:
    app: cronjobattusuarios-path
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: cronjobattusuarios-path