apiVersion: v1
kind: PersistentVolume
metadata:
  name: cronjobattusuarios-path
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: cronjobattusuarios-path
  mountOptions:
    - nolock
  nfs:
    server: storage1
    path: /mnt/storage/storage/kubernetes/ifsc/sje/a/users