apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-postgresql-jaragua-rau
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: netbox-postgresql-jaragua-rau
  mountOptions:
    - nolock
    - nfsvers=3 
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/externos/netbox-jaragua-rau/postgresql/base
