apiVersion: v1
kind: PersistentVolume
metadata:
  name: netbox-postgresql-jaragua-rau
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: netbox-postgresql-jaragua-rau
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/externos/jaragua-rau/postgresql/base
      user: admin
      secretRef:
        name: ceph-secret