apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bareos-sd-continente-conf
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/bareos-sd-continente/
  storageClassName: pv-bareos-sd-continente-conf
  mountOptions:
    - nolock
    - nfsvers=3
 
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-bareos-sd-continente-bkp
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
    targetPortal: 172.18.31.1:3260
    iscsiInterface: default 
    iqn: iqn.1992-04.com.emc:cx.ckm00123700157.a4
    lun: 0
    initiatorName: iqn.2019-06.pv-bareos-sd-continente:00:2955d7e72762
    fsType: ext4
    readOnly: false
    chapAuthDiscovery: true
    chapAuthSession: true
    secretRef:
      name: chap-secret-pv-bareos-sd
  storageClassName: pv-bareos-sd-continente-bkp
