apiVersion: v1
kind: Service
metadata:
  labels:
    app: svc-bareos-sd-continente
  name: svc-bareos-sd-continente
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.7"
    - "191.36.8.25"
  ports:
    - name: bareos
      port: 9103
      protocol: TCP
      targetPort: 9103
  selector:
    app: bareos-sd-continente
  type: LoadBalancer
