apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-root
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-root
  mountOptions:
    - nolock
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/quartus

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-usuarios-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-usuarios-home
  mountOptions:
    - nolock
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-servicos-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-servicos-etc
  mountOptions:
    - nolock
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/users
