apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-root
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-root
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/srv/quartus
      user: admin
      secretRef:
        name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-usuarios-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-usuarios-home
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/home
      user: admin
      secretRef:
        name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: quartus-servicos-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: quartus-servicos-etc
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/users
      user: admin
      secretRef:
        name: ceph-secret
