apiVersion: v1
kind: PersistentVolume
metadata:
  name: criar-usuarios-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: criar-usuarios-home
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/home
      user: admin
      secretRef:
        name: ceph-secret

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: criar-usuarios-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: criar-usuarios-etc
  cephfs:
      monitors:
      - 10.10.10.1:6789
      - 10.10.10.5:6789
      - 10.10.10.6:6789
      path: /kubernetes/ifsc/sje/users/etc
      user: admin
      secretRef:
        name: ceph-secret