apiVersion: v1
kind: Service
metadata:
  name: criar-usuarios
  labels:
    app: criar-usuarios
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2225
      protocol: TCP
      targetPort: 22
  selector:
    app: criar-usuarios
  type: LoadBalancer
