apiVersion: v1
kind: Service
metadata:
  name: criar-usuarios
  labels:
    app: criar-usuarios
spec:
spec:
  externalIPs:
    - "191.36.8.21"
    - "191.36.8.22"
    - "191.36.8.23"
    - "191.36.8.24"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2225
      protocol: TCP
      targetPort: 22
  selector:
    app: criar-usuarios
  type: LoadBalancer
