apiVersion: v1
kind: PersistentVolume
metadata:
  name: nyqlab-home
spec:
  capacity:
    storage: 10011Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nyqlab-users
spec:
  capacity:
    storage: 94Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/users
