apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-mariadb
spec:
  capacity:
    storage: 8890Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/mariadb
    
---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-redis
spec:
  capacity:
    storage: 311Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/redis

---
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-web
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/web
    
---
    
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-fpm-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/nextcloud_fpm/data
