# subpath https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: matlab
  namespace: testes
  labels:
    app: matlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: matlab
    spec:
      containers:
      - name: matlab
        image: cticsjeifsc/matlab
        #securityContext:
        #  privileged: true
        ports:
        - name: ssh
          containerPort: 22
        resources:
            requests:
              cpu: 2
              memory: 2Gi
            limits:
              cpu: 4
              memory: 4Gi
        volumeMounts:
        # Binarios do Matlab
        - name: matlab-root
          mountPath: /opt
        # Home dos usuarios  
        - name: matlab-home
          mountPath: /home
        # etc
        - name: matlab-etc
          mountPath: /etc
        # LDAP          
        - name: nsswitch-ldap-conf
          mountPath: /etc/nsswitch.conf
          subPath: nsswitch.conf
        - name: libnss-ldap-conf
          mountPath: /etc/libnss-ldap.conf
          subPath: libnss-ldap.conf
        - name: pam-ldap-conf
          mountPath: /etc/pam_ldap.conf
          subPath: pam_ldap.conf
        - name: pam-common-session
          mountPath: /etc/pam.d/common-session
          subPath: common-session
        - name: ssh-keys
          mountPath: /root/.ssh/authorized_keys
          subPath: authorized_keys
          readOnly: true
      volumes:
      - name: matlab-root
        persistentVolumeClaim:
          claimName: matlab-root
      - name: matlab-home
        persistentVolumeClaim:
          claimName: matlab-home
      - name: matlab-etc
        persistentVolumeClaim:
          claimName: matlab-etc
      - name: nsswitch-ldap-conf
        configMap:
          name: nsswitch-ldap-conf
      - name: pam-ldap-conf
        configMap:
          name: pam-ldap-conf
      - name: libnss-ldap-conf
        configMap:
          name: libnss-ldap-conf
      - name: pam-common-session
        configMap:
          name: pam-common-session
      - name: ssh-keys
        secret:
          secretName: matlab
