apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: matlab
  namespace: testes
spec:
  minReplicas: 1
  maxReplicas: 10
  metrics:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: matlab
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80

