kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-root
  labels:
    app: matlab-root
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: matlab-root

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-home
  labels:
    app: matlab-home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: matlab-home

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-servicos-etc
  labels:
    app: matlab-servicos-etc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: matlab-servicos-etc
