kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-root
  namespace: testes
  labels:
    app: matlab-root
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: matlab-root

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-home
  namespace: testes
  labels:
    app: matlab-home
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: matlab-home

---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: matlab-etc
  namespace: testes
  labels:
    app: matlab-etc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
  storageClassName: matlab-etc
