apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-root
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: matlab-root
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/saas/srv/matlab/matlab

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-home
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: matlab-home
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/home

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: matlab-servicos-etc
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  storageClassName: matlab-servicos-etc
  mountOptions:
    - nolock
    - nfsvers=3
  nfs:
    server: 191.36.8.71
    path: /nfs_kubernetes/kubernetes/ifsc/sje/a/users
