apiVersion: v1
kind: Service
metadata:
  name: matlab
  labels:
    app: matlab
spec:
  externalIPs:
    - "191.36.8.1"
    - "191.36.8.4"
    - "191.36.8.6"
    - "191.36.8.25"
  ports:
    - name: ssh
      port: 2222
      protocol: TCP
      targetPort: 22
  selector:
    app: matlab
  type: LoadBalancer
